### ISSUE TITLE
Erro ao rodar o npm install

### ISSUE THREAD

**Issue by calcio** [jetebusiness/NEO-Default_Theme#3]
Boa Tarde!
Após fazer o clone do projeto e conforme o README rodar o nmp install simplesmente n instala e logo de cara da o erro:

`NEO-Default_Theme $ npm install

> node-sass@4.10.0 install /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.10.0 postinstall /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.8.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.12
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 12.8.0
gyp verb command install [ '12.8.0' ]
gyp verb install input version string "12.8.0"
gyp verb install installing version: 12.8.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.8.0
gyp verb build dir attempting to create "build" dir: /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/calcio/.node-gyp/12.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/calcio/.node-gyp/12.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/calcio/.node-gyp/12.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/calcio/.node-gyp/12.8.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.4"' -I/home/calcio/.node-gyp/12.8.0/include/node -I/home/calcio/.node-gyp/12.8.0/src -I/home/calcio/.node-gyp/12.8.0/deps/openssl/config -I/home/calcio/.node-gyp/12.8.0/deps/openssl/openssl/include -I/home/calcio/.node-gyp/12.8.0/deps/uv/include -I/home/calcio/.node-gyp/12.8.0/deps/zlib -I/home/calcio/.node-gyp/12.8.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: Command not found
src/libsass.target.mk:158: recipe for target 'Release/obj.target/libsass/src/libsass/src/ast.o' failed
make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
make: Leaving directory '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-55-generic
gyp ERR! command "/usr/bin/node" "/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/node-sass
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.10.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/calcio/.npm/_logs/2019-08-08T19_52_25_560Z-debug.log
calcio@calcio-aspire7 ~/www/Umbrella/NEO-Default_Theme $ npm run watch

> @ watch /home/calcio/www/Umbrella/NEO-Default_Theme
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix-jet/setup/webpack.config.js

internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/laravel-mix-jet/setup/webpack.config.js'
Require stack:
- /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/convert-argv.js
- /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at requireConfig (/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/convert-argv.js:102:15)
    at /home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/webpack.js:171:41
    at Object.Yargs.self.parse (/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/node_modules/yargs/yargs.js:533:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/convert-argv.js',
    '/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix-jet/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/calcio/.npm/_logs/2019-08-08T19_53_10_721Z-debug.log
`
### 2019-08-08T19_53_10_721Z-debug.log

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@6.10.2
3 info using node@v12.8.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 info lifecycle @~watch: @
7 verbose lifecycle @~watch: unsafe-perm in lifecycle true
8 verbose lifecycle @~watch: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/calcio/www/Umbrella/NEO-Default_Theme/node_modules/.bin:/home/calcio/bin:/home/calcio/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle @~watch: CWD: /home/calcio/www/Umbrella/NEO-Default_Theme
10 silly lifecycle @~watch: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix-jet/setup/webpack.config.js'
10 silly lifecycle ]
11 silly lifecycle @~watch: Returned: code: 1  signal: null
12 info lifecycle @~watch: Failed to exec watch script
13 verbose stack Error: @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix-jet/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @
15 verbose cwd /home/calcio/www/Umbrella/NEO-Default_Theme
16 verbose Linux 4.15.0-55-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
18 verbose node v12.8.0
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix-jet/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by calcio** [comment]
Descobri o path novo do arquivo `https://github.com/sass/node-sass/releases/tag/v4.10.0` porém n descobri qual script alterar isso alterar isso.

Tentei fazer instalação pelo `nmp install node-sass` mas tb não deu certo

**Comment by calcio** [comment]
Após algumas semanas mexendo só nos HTMLs no projeto chegou a vez de alterar um script js e como o **npm run watch** ñ estava rodando e com a ajuda do **@Luiz Gustavo** do Slack do Frontend me orientou a olhar o ./resources/js/api/_start.js e decobri que o tal _wishlist.js_ está salvo errado está como _wish**L**ist.js_. Viram a diferença? o L em MAÍSUCULO.

O Linux é CaseSensitive logo ñ achava o arquivo. 

Seria uma boa corrigir isso.
